### PR TITLE
fixes #194 Playlists Page

### LINKED ISSUE #194: Playlists Page
- [x] Add a menu item in the toolbar between `Performers` and `Queue` named `Playlists`
- [x] When you click on `Playlists` in the toolbar it should take you to the Playlists page
- [x] In the Playlists page, there should be a title with text: `Playlists`
- [x] In the Playlists page, we should render each of the playlists in a div (make it look nice)
- [x] Create a function in the `Playlists` Page `./src/Playlists.js` named `loadData()` which will receive no parameters
- [x] In `loadData()` function mock the results, just return an array of `playlist` with `id` and `name` each one
- [x] In the React event `componentDidMount()` call `loadData()` function, and assign the result (which is an array of playlists) to the component state
~Modify the endpoint playLists. The endpoint should return your track list.~

Mock data so we can see how it looks without doing anything on the server/API. If there are fields you need (e.g. Item count), add them to the mock as well. Later we will implement those in the server

### PR DESCRIPTION
**Pull request by ismaelchess**
Fixes #194

### CODE REVIEW

**Comment by ismaelchess** [comment]
add fuction loadMockedData

**Review by mauleyzaola — CHANGES_REQUESTED** [review]
Code looks ok, couple of things missing:

1. The endpoints we currently have won't return that data, unless you plan to make one request for each endpoint. Probably we should have another endpoint that returns each of the playlist with a number (parameter) of items

2. The ui looks so ugly I could have authored it :smile:

**Comment by ismaelchess** [comment]
Another option for the UI.

**Comment by mauleyzaola** [comment]
@ismaelchess Because I don't have your artwork, I cannot see the result :smile: 

Maybe just take a screenshot and put it here instead?

image

**Pull request merged**
